/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { Inject, Injectable } from '@nestjs/common'; import { DataSource } from 'typeorm'; import { DI } from '@/di-symbols.js'; import { Endpoint } from '@/server/api/endpoint-base.js'; import { requireNookCommunityMember, NookCommunityAccessError } from '@/nook/community/access.js'; import { requireNookCommunityChannelAccess, NookCommunityChannelError } from '@/nook/community/channels.js'; import { ApiError } from '../../../../error.js';
const pinSchema = { type: 'object', properties: { id: { type: 'string' }, communityId: { type: 'string' }, channelId: { type: 'string', nullable: true }, kind: { type: 'string' }, targetId: { type: 'string', nullable: true }, url: { type: 'string', nullable: true }, label: { type: 'string', nullable: true }, createdBy: { type: 'string', nullable: true }, createdAt: { type: 'string', format: 'date-time' } }, required: ['id', 'communityId', 'channelId', 'kind', 'targetId', 'url', 'label', 'createdBy', 'createdAt'] } as const;
export const meta = { tags: ['channels'], requireCredential: true, kind: 'read:channels', res: { type: 'array', optional: false, nullable: false, items: pinSchema }, errors: { forbidden: { message: 'You cannot view pins.', code: 'FORBIDDEN', id: '427a470f-3d5b-467c-8d2f-7dbfb27e9547' } } } as const;
export const paramDef = { type: 'object', properties: { communityId: { type: 'string', format: 'misskey:id' }, channelId: { type: 'string', format: 'misskey:id', nullable: true } }, required: ['communityId'] } as const;
@Injectable() export default class extends Endpoint<typeof meta, typeof paramDef> { constructor(@Inject(DI.db) private db: DataSource) { super(meta, paramDef, async (ps, me) => { try { await requireNookCommunityMember(this.db, ps.communityId, me.id); if (ps.channelId != null) await requireNookCommunityChannelAccess(this.db, ps.communityId, me.id, ps.channelId); } catch (error) { if (error instanceof NookCommunityAccessError || error instanceof NookCommunityChannelError) throw new ApiError(meta.errors.forbidden); throw error; } return await this.db.query(`SELECT "id", "communityId", "channelId", "kind", "targetId", "url", "label", "createdBy", "createdAt" FROM "nook_community_pin" WHERE "communityId"=$1 AND ($2::varchar IS NULL AND "channelId" IS NULL OR "channelId"=$2) ORDER BY "createdAt" DESC LIMIT 200`, [ps.communityId, ps.channelId ?? null]); }); } }
