/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { Inject, Injectable } from '@nestjs/common'; import { DataSource } from 'typeorm'; import { DI } from '@/di-symbols.js'; import { IdService } from '@/core/IdService.js'; import { Endpoint } from '@/server/api/endpoint-base.js'; import { requireNookCommunityChannelAccess, NookCommunityChannelError } from '@/nook/community/channels.js'; import { requireNookCommunityPermission, NookCommunityAccessError } from '@/nook/community/access.js'; import { createNookCommunityMessage } from '@/nook/community/messages.js'; import { NookCommunityReferenceError } from '@/nook/community/references.js'; import { serializeNookCommunityMessage } from '@/nook/community/serialize.js'; import { ApiError } from '../../../../error.js';
const messageSchema = { type: 'object', properties: { id: { type: 'string' }, communityId: { type: 'string' }, channelId: { type: 'string' }, userId: { type: 'string', nullable: true }, botId: { type: 'string', nullable: true }, replyToId: { type: 'string', nullable: true }, body: { type: 'string' }, createdAt: { type: 'string', format: 'date-time' }, editedAt: { type: 'string', format: 'date-time', nullable: true } }, required: ['id', 'communityId', 'channelId', 'userId', 'botId', 'replyToId', 'body', 'createdAt', 'editedAt'] } as const;
export const meta = { tags: ['channels'], requireCredential: true, kind: 'write:channels', limit: { duration: 60000, max: 120 }, res: messageSchema, errors: { forbidden: { message: 'You cannot post in this community channel.', code: 'FORBIDDEN', id: '2ee60667-2c2e-4f38-84b9-328c1e04561c' }, invalidReply: { message: 'Reply target must be an active message in the same community channel.', code: 'INVALID_REPLY', id: 'b7bd717c-a572-4a75-a01b-f063916d1c5e' } } } as const;
export const paramDef = { type: 'object', properties: { communityId: { type: 'string', format: 'misskey:id' }, channelId: { type: 'string', format: 'misskey:id' }, body: { type: 'string', minLength: 1, maxLength: 8000 }, replyToId: { type: 'string', format: 'misskey:id', nullable: true } }, required: ['communityId', 'channelId', 'body'] } as const;
@Injectable() export default class extends Endpoint<typeof meta, typeof paramDef> { constructor(@Inject(DI.db) private db: DataSource, private idService: IdService) { super(meta, paramDef, async (ps, me) => { try { await requireNookCommunityPermission(this.db, ps.communityId, me.id, 'messages.post'); const channel = await requireNookCommunityChannelAccess(this.db, ps.communityId, me.id, ps.channelId); if (channel.archivedAt != null || channel.kind === 'voice') throw new NookCommunityChannelError('CHANNEL_FORBIDDEN'); } catch (error) { if (error instanceof NookCommunityAccessError || error instanceof NookCommunityChannelError) throw new ApiError(meta.errors.forbidden); throw error; } try { const message = await createNookCommunityMessage(this.db, this.idService, { communityId: ps.communityId, channelId: ps.channelId, userId: me.id, body: ps.body, replyToId: ps.replyToId ?? null }); return serializeNookCommunityMessage(message); } catch (error) { if (error instanceof NookCommunityReferenceError) throw new ApiError(meta.errors.invalidReply); throw error; } }); } }
