/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { Inject, Injectable } from '@nestjs/common'; import { DataSource } from 'typeorm'; import { DI } from '@/di-symbols.js'; import { Endpoint } from '@/server/api/endpoint-base.js'; import { requireNookCommunityChannelAccess, NookCommunityChannelError } from '@/nook/community/channels.js'; import { listNookCommunityMessages } from '@/nook/community/messages.js'; import { NookCommunityAccessError } from '@/nook/community/access.js'; import { serializeNookCommunityMessage } from '@/nook/community/serialize.js'; import { ApiError } from '../../../../error.js';
const messageSchema = { type: 'object', properties: { id: { type: 'string' }, communityId: { type: 'string' }, channelId: { type: 'string' }, userId: { type: 'string', nullable: true }, botId: { type: 'string', nullable: true }, replyToId: { type: 'string', nullable: true }, body: { type: 'string' }, createdAt: { type: 'string', format: 'date-time' }, editedAt: { type: 'string', format: 'date-time', nullable: true } }, required: ['id', 'communityId', 'channelId', 'userId', 'botId', 'replyToId', 'body', 'createdAt', 'editedAt'] } as const;
export const meta = { tags: ['channels'], requireCredential: true, kind: 'read:channels', res: { type: 'array', optional: false, nullable: false, items: messageSchema }, errors: { forbidden: { message: 'You cannot view this community channel.', code: 'FORBIDDEN', id: '9d4650cb-1da2-4a21-990d-9ed2541111fc' } } } as const;
export const paramDef = { type: 'object', properties: { communityId: { type: 'string', format: 'misskey:id' }, channelId: { type: 'string', format: 'misskey:id' }, limit: { type: 'integer', minimum: 1, maximum: 100 }, before: { type: 'string', format: 'date-time', nullable: true } }, required: ['communityId', 'channelId'] } as const;
@Injectable() export default class extends Endpoint<typeof meta, typeof paramDef> { constructor(@Inject(DI.db) private db: DataSource) { super(meta, paramDef, async (ps, me) => { try { await requireNookCommunityChannelAccess(this.db, ps.communityId, me.id, ps.channelId); } catch (error) { if (error instanceof NookCommunityAccessError || error instanceof NookCommunityChannelError) throw new ApiError(meta.errors.forbidden); throw error; } const messages = await listNookCommunityMessages(this.db, ps.communityId, ps.channelId, ps.limit ?? 50, ps.before == null ? null : new Date(ps.before)); return messages.map(serializeNookCommunityMessage); }); } }
