/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { Inject, Injectable } from '@nestjs/common'; import { DataSource } from 'typeorm'; import { DI } from '@/di-symbols.js'; import { Endpoint } from '@/server/api/endpoint-base.js'; import { requireNookCommunityMember, NookCommunityAccessError } from '@/nook/community/access.js'; import { listNookCommunityEvents } from '@/nook/community/events.js'; import { ApiError } from '../../../../error.js';
const eventSchema = { type: 'object', properties: { id: { type: 'string' }, communityId: { type: 'string' }, creatorId: { type: 'string', nullable: true }, title: { type: 'string' }, description: { type: 'string', nullable: true }, location: { type: 'string', nullable: true }, startsAt: { type: 'string', format: 'date-time' }, endsAt: { type: 'string', format: 'date-time', nullable: true }, maxAttendees: { type: 'number', nullable: true }, textChannelId: { type: 'string', nullable: true }, voiceChannelId: { type: 'string', nullable: true }, cancelledAt: { type: 'string', format: 'date-time', nullable: true }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' }, goingCount: { type: 'number' }, interestedCount: { type: 'number' }, myResponse: { type: 'string', nullable: true } }, required: ['id','communityId','creatorId','title','description','location','startsAt','endsAt','maxAttendees','textChannelId','voiceChannelId','cancelledAt','createdAt','updatedAt','goingCount','interestedCount','myResponse'] } as const;
export const meta = { tags: ['channels'], requireCredential: true, kind: 'read:channels', res: { type: 'array', optional: false, nullable: false, items: eventSchema }, errors: { forbidden: { message: 'You must be a community member.', code: 'FORBIDDEN', id: '75235025-4424-41dd-b9f4-102587121ad2' } } } as const;
export const paramDef = { type: 'object', properties: { communityId: { type: 'string', format: 'misskey:id' }, from: { type: 'string', format: 'date-time', nullable: true }, limit: { type: 'integer', minimum: 1, maximum: 100 } }, required: ['communityId'] } as const;
@Injectable() export default class extends Endpoint<typeof meta, typeof paramDef> { constructor(@Inject(DI.db) private db: DataSource) { super(meta, paramDef, async (ps, me) => { try { await requireNookCommunityMember(this.db, ps.communityId, me.id); } catch (error) { if (error instanceof NookCommunityAccessError) throw new ApiError(meta.errors.forbidden); throw error; } return await listNookCommunityEvents(this.db, ps.communityId, me.id, ps.from == null ? null : new Date(ps.from), ps.limit ?? 50); }); } }
