/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { Inject, Injectable } from '@nestjs/common'; import { DataSource } from 'typeorm'; import { DI } from '@/di-symbols.js'; import { IdService } from '@/core/IdService.js'; import { Endpoint } from '@/server/api/endpoint-base.js'; import { requireNookCommunityPermission, NookCommunityAccessError } from '@/nook/community/access.js'; import { ApiError } from '../../../../error.js';
const announcementSchema = { type: 'object', properties: { id: { type: 'string' }, communityId: { type: 'string' }, authorId: { type: 'string', nullable: true }, title: { type: 'string' }, body: { type: 'string' }, important: { type: 'boolean' }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' }, expiresAt: { type: 'string', format: 'date-time', nullable: true } }, required: ['id', 'communityId', 'authorId', 'title', 'body', 'important', 'createdAt', 'updatedAt', 'expiresAt'] } as const;
export const meta = { tags: ['channels'], requireCredential: true, kind: 'write:channels', res: announcementSchema, errors: { forbidden: { message: 'You cannot manage announcements.', code: 'FORBIDDEN', id: 'ff2d87a5-a2fd-4811-a8b3-45ee7a702748' } } } as const;
export const paramDef = { type: 'object', properties: { communityId: { type: 'string', format: 'misskey:id' }, title: { type: 'string', minLength: 1, maxLength: 160 }, body: { type: 'string', minLength: 1, maxLength: 12000 }, important: { type: 'boolean' }, expiresAt: { type: 'string', format: 'date-time', nullable: true } }, required: ['communityId', 'title', 'body'] } as const;
@Injectable() export default class extends Endpoint<typeof meta, typeof paramDef> { constructor(@Inject(DI.db) private db: DataSource, private idService: IdService) { super(meta, paramDef, async (ps, me) => { try { await requireNookCommunityPermission(this.db, ps.communityId, me.id, 'announcements.manage'); } catch (error) { if (error instanceof NookCommunityAccessError) throw new ApiError(meta.errors.forbidden); throw error; } const rows = await this.db.query('INSERT INTO "nook_community_announcement" ("id", "communityId", "authorId", "title", "body", "important", "expiresAt") VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING "id", "communityId", "authorId", "title", "body", "important", "createdAt", "updatedAt", "expiresAt"', [this.idService.gen(), ps.communityId, me.id, ps.title, ps.body, ps.important ?? false, ps.expiresAt == null ? null : new Date(ps.expiresAt)]); return rows[0]; }); } }
