const device=document.querySelector('#device');const page=document.querySelector('#page');const backdrop=document.querySelector('#composerBackdrop');const text=document.querySelector('#composerText');const count=document.querySelector('#charCount');let route='home';let homeTab='Following';let profileTab='Posts';let posts=[{name:'Nook Preview',handle:'@nook · 2m',text:'デスクトップ版のNook UIデモです。',media:true},{name:'Community',handle:'@community · 8m',text:'Home / Explore / Community / Chatを中心にしたナビゲーション。'}];
const esc=s=>s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function postHTML(p,i=0){return `<article class="post"><div class="postAvatar ${i%2?'alt':''}"></div><div><b>${esc(p.name)}</b> <span>${esc(p.handle)}</span><p>${esc(p.text)}</p>${p.media?'<div class="mediaCard">Preview media</div>':''}<div class="actions">♡ ${12+i}　↻ ${4+i}　☵ ${3+i}</div></div></article>`}
function home(){return `<div class="timelineHeader"><div class="timelineTabs">${['Following','Discover','Media'].map(x=>`<button data-home-tab="${x}" class="${homeTab===x?'selected':''}">${x}</button>`).join('')}</div></div><div class="feed">${posts.filter(p=>homeTab!=='Media'||p.media).map(postHTML).join('')}</div>`}
function explore(){return `<div class="pageHeader"><h2>Explore</h2></div><div class="grid"><div class="card"><b>Trending</b><p><span class="tag">#Nook</span><span class="tag">#MotionDesign</span><span class="tag">#Creative</span></p></div><div class="card"><b>Creators</b><p class="muted">おすすめのクリエイターを探せます。</p></div><div class="card"><b>Media</b><p class="muted">画像・動画付き投稿をまとめて表示。</p></div><div class="card"><b>Communities</b><p class="muted">興味のあるコミュニティを発見。</p></div></div>`}
function community(){return `<div class="pageHeader"><h2>Community</h2></div><div class="list"><div class="card"><b>Popular communities</b><p><span class="tag">Motion Design</span><span class="tag">After Effects</span><span class="tag">Illustration</span></p></div>${['Motion Design','After Effects Scripts','Video Creators'].map((x,i)=>`<div class="listItem"><span class="avatar">${x[0]}</span><div class="listItemText"><b>${x}</b><small>${120+i*84} members</small></div><button class="previewMode">Join</button></div>`).join('')}</div>`}
function chat(){return `<div class="pageHeader"><h2>Chat</h2></div><div class="list">${['Mio','Design Team','Kuro'].map((x,i)=>`<div class="listItem"><span class="avatar">${x[0]}</span><div class="listItemText"><b>${x}</b><small>${i===0?'新しいUI見たよ！':i===1?'3件の新着メッセージ':'またあとで！'}</small></div><span class="muted">${i+1}m</span></div>`).join('')}</div>`}
function notifications(){return `<div class="pageHeader"><h2>Notifications</h2></div><div class="list">${['@motion があなたの投稿にリアクションしました','@design があなたをフォローしました','Community に新しい投稿があります'].map((x,i)=>`<div class="listItem"><span class="avatar">${i+1}</span><div class="listItemText"><b>${x}</b><small>${i+2}分前</small></div></div>`).join('')}</div>`}
function settings(){return `<div class="pageHeader"><h2>Settings</h2></div><div class="list"><div class="settingRow"><span>Dark mode</span><button class="switch on" data-switch></button></div><div class="settingRow"><span>Realtime mode</span><button class="switch" data-switch></button></div><div class="settingRow"><span>Notifications</span><button class="switch on" data-switch></button></div><div class="settingRow"><span>Private likes</span><button class="switch on" data-switch></button></div></div>`}
function profile(){return `<div class="profileHero"><span class="avatar">N</span><h2>Nagisa</h2><div class="muted">@nagisa</div><p>映像・デザイン・Nook開発</p></div><div class="profileTabs">${['Posts','Media','Videos','Works'].map(x=>`<button data-profile-tab="${x}" class="${profileTab===x?'active':''}">${x}</button>`).join('')}</div><div class="feed">${profileTab==='Works'?'<div class="grid"><div class="mediaCard">Work 01</div><div class="mediaCard">Work 02</div></div>':posts.filter(p=>profileTab==='Posts'||p.media).map(postHTML).join('')}</div>`}
function render(){page.innerHTML=({home:home(),explore:explore(),community:community(),chat:chat(),notifications:notifications(),settings:settings(),profile:profile()})[route]||home();document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===route));page.querySelectorAll('[data-home-tab]').forEach(b=>b.onclick=()=>{homeTab=b.dataset.homeTab;render()});page.querySelectorAll('[data-profile-tab]').forEach(b=>b.onclick=()=>{profileTab=b.dataset.profileTab;render()});page.querySelectorAll('[data-switch]').forEach(b=>b.onclick=()=>b.classList.toggle('on'))}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){route=r.dataset.route;render()}});document.querySelectorAll('.previewMode[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.previewMode[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');device.className=`device ${b.dataset.mode}`});function openComposer(){backdrop.hidden=false;text.focus()}document.querySelector('#openComposer').onclick=openComposer;document.querySelector('#mobileCreate').onclick=openComposer;document.querySelector('#closeComposer').onclick=()=>backdrop.hidden=true;backdrop.onclick=e=>{if(e.target===backdrop)backdrop.hidden=true};text.oninput=()=>count.textContent=`${text.value.length} / 280`;document.querySelector('#submitPost').onclick=()=>{const value=text.value.trim();if(!value)return;posts.unshift({name:'Nagisa',handle:'@nagisa · now',text:value});text.value='';count.textContent='0 / 280';backdrop.hidden=true;route='home';homeTab='Following';render()};render();