/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { Inject, Injectable } from '@nestjs/common'; import { DataSource } from 'typeorm'; import { DI } from '@/di-symbols.js'; import { Endpoint } from '@/server/api/endpoint-base.js'; import { NookAccessService } from '@/nook/policy/NookAccessService.js'; import { heartbeatNookCommunityVoice, NookCommunityVoiceError } from '@/nook/community/voice.js'; import { ApiError } from '../../../../error.js';
const configSchema = { type: 'object', properties: { ttsEnabled: { type: 'boolean' }, ttsSourceChannelId: { type: 'string', nullable: true }, ttsLanguage: { type: 'string', nullable: true }, musicEnabled: { type: 'boolean' } }, required: ['ttsEnabled','ttsSourceChannelId','ttsLanguage','musicEnabled'] } as const;
const musicSchema = { type: 'object', nullable: true, properties: { url: { type: 'string', nullable: true }, title: { type: 'string', nullable: true }, positionSeconds: { type: 'number' }, playing: { type: 'boolean' }, updatedAt: { type: 'string', format: 'date-time' } }, required: ['url','title','positionSeconds','playing','updatedAt'] } as const;
export const meta = { tags: ['channels'], requireCredential: true, kind: 'write:channels', limit: { duration: 60000, max: 60 }, res: { type: 'object', optional: false, nullable: false, properties: { peers: { type: 'array', items: { type: 'string' } }, speakingPeerIds: { type: 'array', items: { type: 'string' } }, canSpeak: { type: 'boolean' }, config: configSchema, music: musicSchema }, required: ['peers','speakingPeerIds','canSpeak','config','music'] }, errors: { sessionExpired: { message: 'Voice session expired.', code: 'VOICE_SESSION_EXPIRED', id: 'e00f6834-d7ab-47eb-8cb3-71955e74619e' } } } as const;
export const paramDef = { type: 'object', properties: { channelId: { type: 'string', format: 'misskey:id' }, sessionId: { type: 'string', minLength: 16, maxLength: 64 } }, required: ['channelId','sessionId'] } as const;
@Injectable() export default class extends Endpoint<typeof meta, typeof paramDef> { constructor(@Inject(DI.db) private db: DataSource, private nookAccessService: NookAccessService) { super(meta, paramDef, async (ps, me) => { try { return await heartbeatNookCommunityVoice(this.db, this.nookAccessService, ps.channelId, me.id, ps.sessionId); } catch (error) { if (error instanceof NookCommunityVoiceError) throw new ApiError(meta.errors.sessionExpired); throw error; } }); } }
