/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { Inject, Injectable } from '@nestjs/common'; import { DataSource } from 'typeorm'; import { DI } from '@/di-symbols.js'; import { IdService } from '@/core/IdService.js'; import { Endpoint } from '@/server/api/endpoint-base.js'; import { NookAccessService } from '@/nook/policy/NookAccessService.js'; import { requireNookCommunityPermission, NookCommunityAccessError } from '@/nook/community/access.js'; import { createNookCommunityChannel } from '@/nook/community/channels.js'; import { NookCommunityReferenceError } from '@/nook/community/references.js'; import { serializeNookCommunityChannel } from '@/nook/community/serialize.js'; import { ApiError } from '../../../../error.js';
const channelSchema = { type: 'object', properties: { id: { type: 'string' }, communityId: { type: 'string' }, parentId: { type: 'string', nullable: true }, name: { type: 'string' }, topic: { type: 'string', nullable: true }, kind: { type: 'string' }, position: { type: 'number' }, allowedRoleIds: { type: 'array', items: { type: 'string' } }, archivedAt: { type: 'string', format: 'date-time', nullable: true } }, required: ['id', 'communityId', 'parentId', 'name', 'topic', 'kind', 'position', 'allowedRoleIds', 'archivedAt'] } as const;
export const meta = { tags: ['channels'], requireCredential: true, kind: 'write:channels', res: channelSchema, errors: { forbidden: { message: 'You cannot manage channels.', code: 'FORBIDDEN', id: '0c5c98be-2d71-4dbb-8fc4-bfadd2cf0ccc' }, voiceDisabled: { message: 'Voice calls are disabled.', code: 'NOOK_VOICE_CALL_DISABLED', id: 'fbf7a0ce-ef63-4271-9370-c674e8d73d52', kind: 'permission', httpStatusCode: 403 }, invalidReference: { message: 'A parent channel or role does not belong to this community.', code: 'INVALID_REFERENCE', id: '5bf12cb6-f144-4bf4-829c-e83ab16834db' } } } as const;
export const paramDef = { type: 'object', properties: { communityId: { type: 'string', format: 'misskey:id' }, parentId: { type: 'string', format: 'misskey:id', nullable: true }, name: { type: 'string', minLength: 1, maxLength: 64 }, topic: { type: 'string', maxLength: 1024, nullable: true }, kind: { type: 'string', enum: ['text', 'announcement', 'media', 'forum', 'voice'] }, position: { type: 'integer', minimum: 0, maximum: 10000 }, allowedRoleIds: { type: 'array', maxItems: 100, items: { type: 'string', format: 'misskey:id' } } }, required: ['communityId', 'name', 'kind'] } as const;
@Injectable() export default class extends Endpoint<typeof meta, typeof paramDef> { constructor(@Inject(DI.db) private db: DataSource, private idService: IdService, private nookAccessService: NookAccessService) { super(meta, paramDef, async (ps, me) => { try { await requireNookCommunityPermission(this.db, ps.communityId, me.id, 'channels.manage'); } catch (error) { if (error instanceof NookCommunityAccessError) throw new ApiError(meta.errors.forbidden); throw error; } if (ps.kind === 'voice' && !(await this.nookAccessService.isFeatureEnabled('voice_call'))) throw new ApiError(meta.errors.voiceDisabled); try { const channel = await createNookCommunityChannel(this.db, this.idService, { communityId: ps.communityId, parentId: ps.parentId ?? null, name: ps.name, topic: ps.topic ?? null, kind: ps.kind, position: ps.position ?? 0, allowedRoleIds: ps.allowedRoleIds ?? [] }); return serializeNookCommunityChannel(channel); } catch (error) { if (error instanceof NookCommunityReferenceError) throw new ApiError(meta.errors.invalidReference); throw error; } }); } }
