/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { Inject, Injectable } from '@nestjs/common'; import { DataSource } from 'typeorm'; import { DI } from '@/di-symbols.js'; import { Endpoint } from '@/server/api/endpoint-base.js'; import { NookAccessService } from '@/nook/policy/NookAccessService.js'; import { listNookCommunityChannels } from '@/nook/community/channels.js'; import { NookCommunityAccessError } from '@/nook/community/access.js'; import { ApiError } from '../../../../error.js';
const channelSchema = { type: 'object', properties: { id: { type: 'string' }, communityId: { type: 'string' }, parentId: { type: 'string', nullable: true }, name: { type: 'string' }, topic: { type: 'string', nullable: true }, kind: { type: 'string' }, position: { type: 'number' }, allowedRoleIds: { type: 'array', items: { type: 'string' } }, archivedAt: { type: 'string', format: 'date-time', nullable: true } }, required: ['id', 'communityId', 'parentId', 'name', 'topic', 'kind', 'position', 'allowedRoleIds', 'archivedAt'] } as const;
export const meta = { tags: ['channels'], requireCredential: true, kind: 'read:channels', res: { type: 'array', optional: false, nullable: false, items: channelSchema }, errors: { forbidden: { message: 'You must be a community member.', code: 'FORBIDDEN', id: '8f8e4232-c189-43ab-ab92-6baaa641c0a2' } } } as const;
export const paramDef = { type: 'object', properties: { communityId: { type: 'string', format: 'misskey:id' } }, required: ['communityId'] } as const;
@Injectable() export default class extends Endpoint<typeof meta, typeof paramDef> { constructor(@Inject(DI.db) private db: DataSource, private nookAccessService: NookAccessService) { super(meta, paramDef, async (ps, me) => { try { const channels = await listNookCommunityChannels(this.db, ps.communityId, me.id); if (await this.nookAccessService.isFeatureEnabled('voice_call')) return channels; return channels.filter(channel => channel.kind !== 'voice'); } catch (error) { if (error instanceof NookCommunityAccessError) throw new ApiError(meta.errors.forbidden); throw error; } }); } }
