<!--
SPDX-FileCopyrightText: syuilo and misskey-project
SPDX-License-Identifier: AGPL-3.0-only
-->
<template>
<section class="_gaps">
	<div v-if="can('community.manage')" class="_panel" :class="$style.box"><h3>{{ l.settings }}</h3><label>Join mode <select v-model="joinMode"><option value="open">open</option><option value="approval">approval</option><option value="invite">invite</option><option value="private">private</option></select></label><label><input v-model="discoverable" type="checkbox"> Discoverable</label><button class="_button" @click="saveSettings">{{ l.save }}</button></div>
	<div v-if="can('channels.manage')" class="_panel" :class="$style.box"><h3>{{ l.channels }}</h3><div v-for="channel in channels" :key="channel.id">{{ channel.kind==='voice'?'🔊':'#' }} {{ channel.name }}</div><form @submit.prevent="createChannel"><input v-model="channelName" required maxlength="64" placeholder="Channel name"><select v-model="channelKind"><option value="text">text</option><option value="announcement">announcement</option><option value="media">media</option><option value="forum">forum</option><option v-if="voiceEnabled" value="voice">voice</option></select><button class="_button">{{ l.create }}</button></form></div>
	<div v-if="can('roles.manage')" class="_panel" :class="$style.box"><h3>{{ l.role }}</h3><div v-for="role in roles" :key="role.id"><span :style="{color:role.color||undefined}">{{ role.name }}</span> <small>{{ role.permissions.join(', ') }}</small> <button class="_button" @click="deleteRole(role.id)">×</button></div><form @submit.prevent="createRole"><input v-model="roleName" required maxlength="64" placeholder="Role name"><input v-model="rolePermissions" placeholder="messages.post, events.manage"><button class="_button">{{ l.create }}</button></form></div>
	<div v-if="can('rules.manage')" class="_panel" :class="$style.box"><h3>{{ l.rules }}</h3><article v-for="rule in rules" :key="rule.id"><strong>{{ rule.title }}</strong><p>{{ rule.body }}</p><button class="_button" @click="deleteRule(rule.id)">×</button></article><form @submit.prevent="createRule"><input v-model="ruleTitle" required maxlength="128" placeholder="Rule"><textarea v-model="ruleBody" required maxlength="4096"></textarea><button class="_button">{{ l.create }}</button></form></div>
	<div v-if="can('members.invite')" class="_panel" :class="$style.box"><h3>{{ l.invite }}</h3><button class="_button" @click="createInvite">{{ l.create }}</button><div v-if="inviteToken" :class="$style.token"><code>{{ inviteToken }}</code><button class="_button" @click="copyInvite">{{ l.copy }}</button></div><div v-for="invite in invites" :key="invite.id"><small>{{ invite.id }} · {{ invite.useCount }}/{{ invite.maxUses??'∞' }}</small> <button class="_button" @click="revokeInvite(invite.id)">Revoke</button></div></div>
	<div v-if="can('pins.manage')" class="_panel" :class="$style.box"><h3>{{ l.pins }}</h3><div v-for="pin in pins" :key="pin.id">📌 {{ pin.label||pin.url||pin.targetId }} <button class="_button" @click="deletePin(pin.id)">×</button></div><form @submit.prevent="createPin"><select v-model="pinKind"><option value="url">url</option><option value="note">note</option><option value="message">message</option><option value="announcement">announcement</option><option value="event">event</option></select><input v-model="pinTarget" placeholder="URL or target ID"><input v-model="pinLabel" placeholder="Label"><button class="_button">{{ l.create }}</button></form></div>
</section>
</template>
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue';import { nookApi } from './nook-api.js';import { communityLabels as l } from './labels.js';import type { CommunityChannel,CommunityDetail,CommunityPin,CommunityRole,CommunityRule } from './types.js';
const props=defineProps<{communityId:string;detail:CommunityDetail;voiceEnabled:boolean}>();const emit=defineEmits<{refresh:[]}>();const joinMode=ref(props.detail.joinMode);const discoverable=ref(props.detail.discoverable);const channels=ref<CommunityChannel[]>([]);const roles=ref<CommunityRole[]>([]);const rules=ref<CommunityRule[]>([]);const invites=ref<Array<{id:string;useCount:number;maxUses:number|null}>>([]);const pins=ref<CommunityPin[]>([]);const channelName=ref('');const channelKind=ref<CommunityChannel['kind']>('text');const roleName=ref('');const rolePermissions=ref('messages.post');const ruleTitle=ref('');const ruleBody=ref('');const inviteToken=ref('');const pinKind=ref<'url'|'note'|'message'|'announcement'|'event'>('url');const pinTarget=ref('');const pinLabel=ref('');
function can(permission:string){const values=props.detail.membership?.permissions??[];return values.includes('*')||values.includes(permission);}
async function safe<T>(request:Promise<T>,fallback:T):Promise<T>{try{return await request;}catch{return fallback;}}
async function load(){const requests:Promise<void>[]=[];if(can('channels.manage'))requests.push(safe(nookApi<CommunityChannel[]>('nook/community/channels/list',{communityId:props.communityId}),[]).then(value=>{channels.value=value;}));if(can('roles.manage'))requests.push(safe(nookApi<CommunityRole[]>('nook/community/roles/list',{communityId:props.communityId}),[]).then(value=>{roles.value=value;}));if(can('rules.manage'))requests.push(safe(nookApi<CommunityRule[]>('nook/community/rules/list',{communityId:props.communityId}),[]).then(value=>{rules.value=value;}));if(can('members.invite'))requests.push(safe(nookApi<Array<{id:string;useCount:number;maxUses:number|null}>>('nook/community/invites/list',{communityId:props.communityId}),[]).then(value=>{invites.value=value;}));if(can('pins.manage'))requests.push(safe(nookApi<CommunityPin[]>('nook/community/pins/list',{communityId:props.communityId,channelId:null}),[]).then(value=>{pins.value=value;}));await Promise.all(requests);}
async function saveSettings(){await nookApi('nook/community/settings-update',{communityId:props.communityId,joinMode:joinMode.value,discoverable:discoverable.value});emit('refresh');}
async function createChannel(){if(channelKind.value==='voice'&&!props.voiceEnabled)return;await nookApi('nook/community/channels/create',{communityId:props.communityId,name:channelName.value,kind:channelKind.value});channelName.value='';await load();}
async function createRole(){await nookApi('nook/community/roles/create',{communityId:props.communityId,name:roleName.value,permissions:rolePermissions.value.split(',').map(x=>x.trim()).filter(Boolean)});roleName.value='';await load();}
async function deleteRole(roleId:string){await nookApi('nook/community/roles/delete',{communityId:props.communityId,roleId});await load();}
async function createRule(){await nookApi('nook/community/rules/create',{communityId:props.communityId,title:ruleTitle.value,body:ruleBody.value});ruleTitle.value='';ruleBody.value='';await load();}
async function deleteRule(ruleId:string){await nookApi('nook/community/rules/delete',{communityId:props.communityId,ruleId});await load();}
async function createInvite(){const result=await nookApi<{token:string}>('nook/community/invites/create',{communityId:props.communityId});inviteToken.value=result.token;await load();}
async function copyInvite(){await navigator.clipboard.writeText(`${location.origin}/channels/${props.communityId}?invite=${encodeURIComponent(inviteToken.value)}`);}
async function revokeInvite(inviteId:string){await nookApi('nook/community/invites/revoke',{communityId:props.communityId,inviteId});await load();}
async function createPin(){const data:Record<string,unknown>={communityId:props.communityId,kind:pinKind.value,label:pinLabel.value||null};if(pinKind.value==='url')data.url=pinTarget.value;else data.targetId=pinTarget.value;await nookApi('nook/community/pins/create',data);pinTarget.value='';pinLabel.value='';await load();}
async function deletePin(pinId:string){await nookApi('nook/community/pins/delete',{communityId:props.communityId,pinId});await load();}
watch(()=>props.detail,detail=>{joinMode.value=detail.joinMode;discoverable.value=detail.discoverable;if(!props.voiceEnabled&&channelKind.value==='voice')channelKind.value='text';void load();},{deep:true});onMounted(load);
</script>
<style module>.box{padding:16px}.box h3{margin-top:0}.box form{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.box input,.box textarea,.box select{padding:8px;background:var(--MI_THEME-bg);color:var(--MI_THEME-fg);border:1px solid var(--MI_THEME-divider);border-radius:7px}.token{margin:10px 0;padding:8px;background:var(--MI_THEME-bg);overflow-wrap:anywhere}</style>
