/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { Inject, Injectable } from '@nestjs/common'; import { DataSource } from 'typeorm'; import { DI } from '@/di-symbols.js'; import { Endpoint } from '@/server/api/endpoint-base.js'; import { listNookCommunityChannels } from '@/nook/community/channels.js'; import { NookCommunityAccessError } from '@/nook/community/access.js'; import { ApiError } from '../../../error.js';
const resultSchema = { type: 'object', properties: { id: { type: 'string' }, channelId: { type: 'string' }, userId: { type: 'string', nullable: true }, botId: { type: 'string', nullable: true }, body: { type: 'string' }, createdAt: { type: 'string', format: 'date-time' } }, required: ['id', 'channelId', 'userId', 'botId', 'body', 'createdAt'] } as const;
export const meta = { tags: ['channels'], requireCredential: true, kind: 'read:channels', res: { type: 'array', optional: false, nullable: false, items: resultSchema }, errors: { forbidden: { message: 'You must be a community member.', code: 'FORBIDDEN', id: 'a0bb2413-5da4-4420-a840-43cd0f59b134' } } } as const;
export const paramDef = { type: 'object', properties: { communityId: { type: 'string', format: 'misskey:id' }, query: { type: 'string', minLength: 1, maxLength: 256 }, channelId: { type: 'string', format: 'misskey:id', nullable: true }, limit: { type: 'integer', minimum: 1, maximum: 100 } }, required: ['communityId', 'query'] } as const;
@Injectable() export default class extends Endpoint<typeof meta, typeof paramDef> { constructor(@Inject(DI.db) private db: DataSource) { super(meta, paramDef, async (ps, me) => { let channels; try { channels = await listNookCommunityChannels(this.db, ps.communityId, me.id); } catch (error) { if (error instanceof NookCommunityAccessError) throw new ApiError(meta.errors.forbidden); throw error; } const visibleIds = channels.map(channel => channel.id).filter(id => ps.channelId == null || id === ps.channelId); if (visibleIds.length === 0) return []; return await this.db.query(`SELECT "id", "channelId", "userId", "botId", "body", "createdAt" FROM "nook_community_message" WHERE "communityId"=$1 AND "channelId" = ANY($2::varchar[]) AND "deletedAt" IS NULL AND "body" ILIKE '%' || $3 || '%' ORDER BY "createdAt" DESC LIMIT $4`, [ps.communityId, visibleIds, ps.query, ps.limit ?? 50]); }); } }
