/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { Inject, Injectable } from '@nestjs/common'; import { DataSource } from 'typeorm'; import { DI } from '@/di-symbols.js'; import { Endpoint } from '@/server/api/endpoint-base.js'; import { requireNookCommunityPermission, NookCommunityAccessError } from '@/nook/community/access.js'; import { ApiError } from '../../../../error.js';
const botSchema = { type: 'object', properties: { id: { type: 'string' }, communityId: { type: 'string' }, creatorId: { type: 'string', nullable: true }, name: { type: 'string' }, description: { type: 'string', nullable: true }, kind: { type: 'string' }, scopes: { type: 'array', items: { type: 'string' } }, allowedChannelIds: { type: 'array', items: { type: 'string' } }, enabled: { type: 'boolean' }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' }, lastUsedAt: { type: 'string', format: 'date-time', nullable: true } }, required: ['id','communityId','creatorId','name','description','kind','scopes','allowedChannelIds','enabled','createdAt','updatedAt','lastUsedAt'] } as const;
export const meta = { tags: ['channels'], requireCredential: true, kind: 'read:channels', res: { type: 'array', optional: false, nullable: false, items: botSchema }, errors: { forbidden: { message: 'You cannot manage bots.', code: 'FORBIDDEN', id: '86642cd8-6876-4351-b65e-0259416d27cb' } } } as const;
export const paramDef = { type: 'object', properties: { communityId: { type: 'string', format: 'misskey:id' } }, required: ['communityId'] } as const;
@Injectable() export default class extends Endpoint<typeof meta, typeof paramDef> { constructor(@Inject(DI.db) private db: DataSource) { super(meta, paramDef, async (ps, me) => { try { await requireNookCommunityPermission(this.db, ps.communityId, me.id, 'bots.manage'); } catch (error) { if (error instanceof NookCommunityAccessError) throw new ApiError(meta.errors.forbidden); throw error; } return await this.db.query(`SELECT "id","communityId","creatorId","name","description","kind","scopes","allowedChannelIds","enabled","createdAt","updatedAt","lastUsedAt" FROM "nook_community_bot" WHERE "communityId"=$1 ORDER BY "createdAt" ASC`, [ps.communityId]); }); } }
